#!/bin/sh
### BEGIN INIT INFO
# Provides:          ...
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: servicio firmador estatal
# Description:
#
### END INIT INFO
SERVICE_NAME=firmador-servicio
PATH_TO_JAR=/usr/bin/FirmadorServicio/FirmadorServidor.jar
PID_PATH_NAME=/tmp/firmador-servicio
case $1 in
    start)
        echo "Iniciando $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME ]; then
            sudo nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null & echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME Iniciado ..."
        else
            echo "$SERVICE_NAME ya esta Iniciado ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME Deteniendo ..."
            kill $PID;
            echo "$SERVICE_NAME Detenido ..."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME no esta Iniciado ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME Deteniendo ...";
            kill $PID;
            echo "$SERVICE_NAME Detenido ...";
            rm $PID_PATH_NAME
            echo "$SERVICE_NAME Iniciando ..."
            sudo nohup java -jar $PATH_TO_JAR /tmp 2>> /dev/null >> /dev/null & echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME Iniciado ..."
        else
            echo "$SERVICE_NAME no esta Iniciado ..."
        fi
    ;;
    status)
        if [ -f $PID_PATH_NAME ]; then
            echo "$SERVICE_NAME Iniciado ..."
        else
            echo "$SERVICE_NAME no esta Iniciado ..."
        fi
    ;;
esac
