#!/share/sh
### BEGIN INIT INFO
# Autor: Angel Céspedes Quiroz
# Skype: acq1305
# LinkedIn: https://bo.linkedin.com/in/acq1305
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: servicio firmador estatal
# Description: Script que llama a archivos sh
#
### END INIT INFO
SERVICE_NAME=firmador-servicio
case $1 in
    start)
        echo "Iniciando $SERVICE_NAME ..."
        sudo sh /usr/share/FirmadorServicio/config/myapp-start.sh
        echo "$SERVICE_NAME Iniciado ..."
    ;;
    stop)
        echo "$SERVICE_NAME Deteniendo ..."
        sudo sh /usr/share/FirmadorServicio/config/myapp-stop.sh
        echo "$SERVICE_NAME Detenido ..."
    ;;
    restart)
        echo "$SERVICE_NAME Deteniendo ..."
        sudo sh /usr/share/FirmadorServicio/config/myapp-stop.sh
        echo "$SERVICE_NAME Detenido ..."
        echo "Iniciando $SERVICE_NAME ..."
        sudo sh /usr/share/FirmadorServicio/config/myapp-start.sh
        echo "$SERVICE_NAME Iniciado ..."
    ;;
    status)
        sudo sh /usr/share/FirmadorServicio/config/myapp-status.sh
    ;;
esac
